language: node_js
node_js:
  - "12.18"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn eslint:check
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
deploy:
  provider: script
  script: "yarn release"
  skip_cleanup: true
  on:
    node: "12.18"
    branches:
      only: master
