export enum ExceptionType  {
    MISSING_API_KEY = 'MISSING_API_KEY',
    MISSING_PARAMETER = 'MISSING_PARAMETER',
    INVALID_PARAMETER = 'INVALID_PARAMETER',
    VIEW_NOT_READY = 'VIEW_NOT_READY',
}