export enum RequestType {
    LOGIN = 'LOGIN',
    SEND_OTP_REGISTER = 'SEND_OTP_REGISTER',
    VERIFY_OTP_REGISTER = 'VERIFY_OTP_REGISTER',
    GENERATE_ENCRYPTION_KEY = 'GENERATE_ENCRYPTION_KEY',
    ENCRYPT_KEY = 'ENCRYPT_KEY',
    SEND_OTP_LOGIN = 'SEND_OTP_LOGIN',
    VERIFY_OTP_LOGIN = 'VERIFY_OTP_LOGIN',
}